// Generated by CoffeeScript 1.6.3
(function() {
  var $site, createWindow, link, links, site, _i, _len;

  site = localStorage['site'];

  $site = document.getElementById('site');

  $site.value = site;

  links = document.getElementsByTagName('a');

  for (_i = 0, _len = links.length; _i < _len; _i++) {
    link = links[_i];
    link.addEventListener('click', function(e) {
      e.preventDefault();
      return createWindow(this.id);
    });
  }

  createWindow = function(id) {
    site = $site.value;
    localStorage['site'] = site;
    return chrome.runtime.sendMessage({
      createWindow: true,
      params: {
        device: id,
        site: site
      }
    }, function(response) {
      return console.log(response.farewell);
    });
  };

}).call(this);
